In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data = pd.read_csv("/content/drive/MyDrive/Preprocessing/DataPreprocessing.csv")
data.head(10)

,Region,Age,Income,Online Shopper
0,India,49.0,86400.0,No
1,Brazil,32.0,57600.0,Yes
2,USA,35.0,64800.0,No
3,Brazil,43.0,73200.0,No
4,USA,45.0,NaN,Yes
5,India,40.0,69600.0,Yes
6,Brazil,NaN,62400.0,No
7,India,53.0,94800.0,Yes
8,USA,55.0,99600.0,No
9,India,42.0,80400.0,Yes


In [4]:
X = data.iloc[:,:-1].values
Y = data.iloc[:,-1].values

In [5]:
print(X)
print("=======================================")
print(Y)

[['India' 49.0 86400.0]
 ['Brazil' 32.0 57600.0]
 ['USA' 35.0 64800.0]
 ['Brazil' 43.0 73200.0]
 ['USA' 45.0 nan]
 ['India' 40.0 69600.0]
 ['Brazil' nan 62400.0]
 ['India' 53.0 94800.0]
 ['USA' 55.0 99600.0]
 ['India' 42.0 80400.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
data.describe()

,Age,Income
count,9.000000,9.000000
mean,43.777778,76533.333333
std,7.693793,14718.695594
min,32.000000,57600.000000
25%,40.000000,64800.000000
50%,43.000000,73200.000000
75%,49.000000,86400.000000
max,55.000000,99600.000000


In [8]:
data.isnull().sum()

,0
Region,0
Age,1
Income,1
Online Shopper,0


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(X[:,1:])
X[:,1:3] = imputer.transform(X[:,1:])

In [11]:
print(X)

[['India' 49.0 86400.0]
 ['Brazil' 32.0 57600.0]
 ['USA' 35.0 64800.0]
 ['Brazil' 43.0 73200.0]
 ['USA' 45.0 76533.33333333333]
 ['India' 40.0 69600.0]
 ['Brazil' 43.77777777777778 62400.0]
 ['India' 53.0 94800.0]
 ['USA' 55.0 99600.0]
 ['India' 42.0 80400.0]]


In [16]:
newdata = np.array([
    ["USA", 12.0, np.nan]
])

newdata = imputer.transform(newdata[:, 1:])
print(newdata)

[[1.20000000e+01 7.65333333e+04]]


In [17]:
with open("imputer.pkl", "wb") as f:
    pickle.dump(imputer, f)

In [18]:
with open("imputer.pkl", "rb") as f:
    imputer = pickle.load(f)

In [20]:
newdata = np.array([
    ["Brazil", np.nan, np.nan]
])

newdata = imputer.transform(newdata[:,1:])
print(newdata)

[[4.37777778e+01 7.65333333e+04]]


In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler

In [24]:
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:,0])
print(X)

[[1 49.0 86400.0]
 [0 32.0 57600.0]
 [2 35.0 64800.0]
 [0 43.0 73200.0]
 [2 45.0 76533.33333333333]
 [1 40.0 69600.0]
 [0 43.77777777777778 62400.0]
 [1 53.0 94800.0]
 [2 55.0 99600.0]
 [1 42.0 80400.0]]


In [25]:
ct = ColumnTransformer(transformers=[("Country", OneHotEncoder(), [0])], remainder="passthrough")
X = ct.fit_transform(X)
print(X)

[[0.0 1.0 0.0 49.0 86400.0]
 [1.0 0.0 0.0 32.0 57600.0]
 [0.0 0.0 1.0 35.0 64800.0]
 [1.0 0.0 0.0 43.0 73200.0]
 [0.0 0.0 1.0 45.0 76533.33333333333]
 [0.0 1.0 0.0 40.0 69600.0]
 [1.0 0.0 0.0 43.77777777777778 62400.0]
 [0.0 1.0 0.0 53.0 94800.0]
 [0.0 0.0 1.0 55.0 99600.0]
 [0.0 1.0 0.0 42.0 80400.0]]


In [27]:
data["Region"].unique()

array(['India', 'Brazil', 'USA'], dtype=object)

In [29]:
Sta_Scal = StandardScaler()
X = Sta_Scal.fit_transform(X)
print(X)

[[-0.65465367  1.22474487 -0.65465367  0.75887436  0.74947325]
 [ 1.52752523 -0.81649658 -0.65465367 -1.71150388 -1.43817841]
 [-0.65465367 -0.81649658  1.52752523 -1.27555478 -0.89126549]
 [ 1.52752523 -0.81649658 -0.65465367 -0.11302384 -0.25320042]
 [-0.65465367 -0.81649658  1.52752523  0.17760889  0.        ]
 [-0.65465367  1.22474487 -0.65465367 -0.54897294 -0.52665688]
 [ 1.52752523 -0.81649658 -0.65465367  0.         -1.0735698 ]
 [-0.65465367  1.22474487 -0.65465367  1.34013983  1.38753832]
 [-0.65465367 -0.81649658  1.52752523  1.63077256  1.75214693]
 [-0.65465367  1.22474487 -0.65465367 -0.25834021  0.29371249]]


In [30]:
# Save Label_Encoder Model
with open("Label_Encoder.pkl", "wb") as f:
    pickle.dump(le, f)

In [31]:
# Save Column_Transformer Model
with open("Column_Transformer.pkl", "wb") as f:
    pickle.dump(ct, f)

In [32]:
# Save Standard_Scalar Model
with open("Standard_Scalar.pkl", "wb") as f:
    pickle.dump(Sta_Scal, f)